name: "Trigger Jenkins Multiple Jobs"
description: "Triggering Jenkins Job through the API"
author: "Bo-Yi Wu"
inputs:
  url:
    description: "jenkins base url"
  user:
    description: "jenkins username"
  token:
    description: "jenkins api token"
  job:
    description: "jenkins job"
  insecure:
    description: "insecure skip verify"
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "check-circle"
  color: "green"
